[package]
name = "base"
edition.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true

alloy.workspace = true
secp256k1.workspace = true
url.workspace = true
log.workspace = true
base64.workspace = true
