[package]
name = "proof-submitter"
edition.workspace = true
version.workspace = true

[dependencies]
clap.workspace = true
actix-web = "4.9.0"
awc = "3"
alloy.workspace = true
serde.workspace = true
serde_json.workspace = true
prover.workspace = true
base.workspace = true
env_logger.workspace = true