[package]
name = "multi-prover"
edition.workspace = true
version.workspace = true

[features]
default = []
tdx = []

[dependencies]
raiko-core.workspace = true
prover.workspace = true
executor.workspace = true
env_logger.workspace = true
log.workspace = true
secp256k1.workspace = true
rand.workspace = true
actix-web = "4.9.0"
base.workspace = true
hex.workspace = true
tee.workspace = true
alloy.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true